version: "3.8"
services:
  # Main
  todolistapp-service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: todolistapp-main
    restart: always
    ports:
      - ${SERVER_HOST_PORT}:8080
    depends_on:
      todolistapp-db:
        condition: service_healthy
    image: todolistapp-main:latest

    environment:
      - WAIT_HOSTS=todolistapp-db:5432
      - SPRING_DATASOURCE_URL=jdbc:postgresql://todolistapp-db:5432/task
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # Database
  todolistapp-db:
    image: postgres:14.5-alpine
    container_name: todolistapp_db
    restart: always
    volumes:
      - /var/lib/postgresql/data/
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_HOST_PORT}:5432
    # переменные окружения
    environment:
      POSTGRES_DB: task
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5