name: Deploy docker image

on:
  push:
    branches:
      - 'master'

jobs:
  build_docker_image:
    name: Build docker and push
    runs-on: ubuntu-latest
    steps:
      #Build JAR:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 17
      - name: Maven Package
        run: mvn -B clean compile package -DskipTests


